import { useEffect, useState } from 'react';
import { BookOpenText, Plus, Trash2 } from 'lucide-react';
import { adminAPI } from '../api';

const emptyForm = { title: '', slug: '', summary: '', content: '', image: '', status: 'draft' };

//渲染:渲染AdminArticles组件或页面内容
export default function AdminArticles() {
  const [articles, setArticles] = useState([]);
  const [form, setForm] = useState(emptyForm);
  const [message, setMessage] = useState('');
  const [saving, setSaving] = useState(false);
  const load = () => {
                 //处理回调函数逻辑
                 return adminAPI.getArticles().then(setArticles).catch((error) => {
                                                                      //处理异步请求异常
                                                                      return setMessage(error.message);
                                                                    });
               };
  useEffect(() => {
              //执行组件副作用逻辑
               load(); }, []);
  const update = (event) => {
                   //处理回调函数逻辑
                   return setForm({ ...form, [event.target.name]: event.target.value });
                 };
  const submit = async (event) => {
                   //处理回调函数逻辑

    event.preventDefault(); setSaving(true); setMessage('');
    try { await adminAPI.createArticle(form); setForm(emptyForm); setMessage('Article saved. Rebuild the site before publishing it as an SEO page.'); await load(); }
    catch (error) { setMessage(error.message); } finally { setSaving(false); }
  };
  const remove = async (id) => {
                   //处理回调函数逻辑
                    if (!window.confirm('Delete this article record?')) return; await adminAPI.deleteArticle(id); await load(); };
  return (
    <div className="min-h-screen bg-slate-50 pb-16 pt-24"><main className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><header className="mb-8"><p className="mb-2 text-sm font-semibold uppercase tracking-wider text-primary">Administrator</p><h1 className="font-heading text-4xl font-bold text-slate-900">News-blog article upload</h1><p className="mt-2 text-slate-500">Prepare structured article records for editorial review and publication.</p></header><div className="grid gap-8 lg:grid-cols-[1fr_.9fr]"><form onSubmit={submit} className="rounded-3xl border border-slate-200 bg-white p-7 shadow-sm"><h2 className="mb-6 flex items-center gap-2 font-heading text-2xl font-bold"><Plus className="text-primary" />New article</h2><div className="space-y-5">{[['title','Article title *'],['slug','URL slug (optional)'],['summary','Search summary *'],['image','Cover image URL']].map(([name,label]) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            //渲染:渲染列表内容
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return <label key={name} className="block"><span className="mb-2 block text-sm font-semibold text-slate-700">{label}</span><input name={name} required={name === 'title' || name === 'summary'} value={form[name]} onChange={update} className="w-full rounded-xl border-slate-300" /></label>;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          })}<label className="block"><span className="mb-2 block text-sm font-semibold text-slate-700">Article content *</span><textarea name="content" required rows="12" value={form.content} onChange={update} className="w-full rounded-xl border-slate-300" /></label><label className="block"><span className="mb-2 block text-sm font-semibold text-slate-700">Status</span><select name="status" value={form.status} onChange={update} className="w-full rounded-xl border-slate-300"><option value="draft">Draft</option><option value="review">Ready for review</option><option value="published">Published record</option></select></label></div>{message && <p className="mt-5 rounded-xl bg-orange-50 p-4 text-sm text-orange-800">{message}</p>}<button disabled={saving} className="mt-6 rounded-xl bg-primary px-6 py-3 font-semibold text-white disabled:opacity-50">{saving ? 'Saving…' : 'Save article'}</button></form><section className="rounded-3xl border border-slate-200 bg-white p-7 shadow-sm"><h2 className="mb-6 flex items-center gap-2 font-heading text-2xl font-bold"><BookOpenText className="text-primary" />Article records</h2><div className="space-y-3">{articles.map((article) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         //渲染:渲染列表内容
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         return <article key={article.id} className="rounded-2xl border border-slate-200 p-5"><div className="flex items-start justify-between gap-4"><div><span className="text-xs font-semibold uppercase tracking-wider text-primary">{article.status}</span><h3 className="mt-1 font-semibold text-slate-900">{article.title}</h3><p className="mt-1 text-sm text-slate-500">/{article.slug}</p></div><button onClick={() => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 //处理页面交互事件
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 return remove(article.id);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               }} className="text-slate-400 hover:text-red-600" title="Delete"><Trash2 size={18} /></button></div></article>;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       })}{articles.length === 0 && <p className="text-slate-500">No uploaded article records yet.</p>}</div></section></div></main></div>
  );
}
